<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'category_id' => '1',
                'user_id' => '2',
                'name' => 'Playstation 5',
                'description' => 'Playstation 5',
                'quantity' => 1,
                'state' => 'S',
                'price' => 2000.0,
                'discount_price' => 1900.0,
                'image' => 'upload/jwgoNfuJlXMDJ5SibyJFTC7BtwaI1GtkxwTwWbUh.jpg',
                'amount_sales' => 10,
                'information' => 'Velocidad sorprendente Disfruta de la potencia de una CPU, una GPU y una SSD personalizadas con E/S integradas que redefinirán lo que una consola PlayStation puede hacer. SSD de velocidad ultrarrápida Aprovecha al máximo tus sesiones de juego con tiempos de carga casi instantáneos para los juegos instalados en la PS5 E/S integradas La integración personalizada de los sistemas de la consola PS5 les permite a los creadores obtener datos desde la SSD tan rápido que pueden diseñar juegos de maneras que antes no eran posibles. Más características de la consola PS5 Retrocompatibilidad Disfruta de un catálogo retrocompatible de juegos de PS4™ en tu consola PS5. Mejoras para juegos Disfruta de frecuencias de imágenes más rápidas y fluidas en juegos específicos de PS4 y PS VR. Actualiza tus juegos de PS4 a versiones digitales de PS5 La consola PS5 les ofrece a los distribuidores de juegos la capacidad de permitirles a los jugadores actualizar las versiones en disco y digitales de sus juegos de PS4 a juegos digitales de PS51. Integración de PlayStation®VR Conecta tu PlayStation VR a tu consola PS5 para disfrutar de los juegos de PS VR compatibles. Para configurar tu PS VR con la consola PS5, necesitarás la PlayStation Camera2 para PS4 y un adaptador para PlayStation Camera',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '9',
                'user_id' => '3',
                'name' => 'Celular',
                'description' => 'Samsung Galaxy S20',
                'quantity' => 1,
                'state' => 'S',
                'price' => 1500.0,
                'discount_price' => 1400.0,
                'image' => 'upload/3Oeisd4iRGZKBdGSmNonWzrEOK9LYG08RrKsFYcp.jpg',
                'amount_sales' => 12,
                'information' => 'El samsung galaxy s20 fan edition ofrece varias opciones en cuanto a colores, además su acabado lo hace ver elegante. asimismo, con sus 4 curvaturas a los lados le permite a cualquiera mantener un mejor agarre. su pantalla infinity-o es una dynamic amoled de 6.5 pulgadas con resolución full hd+ que ofrece una tasa de refrescamiento de 120hz, de esa manera tendrás una mejor experiencia de navegación sin tanta vibración. 
                por otro lado, posee un lector de huella digital que se encuentra en la pantalla y su cámara frontal casi ni se percibe. su aspecto es de 20:9, el espacio suficiente para disfrutar de series, películas, juegos y más. la pantalla del galaxy s20 fe cuenta con una tasa de refresco de 120hz (la más rápida) lo que te permite ver videos de gran calidad así como disfrutar de juegos de tipo fps como fornite, cod mobile o free fire.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '2',
                'name' => 'Coputadora HP',
                'description' => "Laptop HP DQ2055WM 4gb 256gb SSD 14'",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1000.0,
                'discount_price' => 990.0,
                'image' => 'upload/LsaJ9FDjaxQtW3fTBSRAI6tnqGmBGTYaQFtGFiCd.jpg',
                'amount_sales' => 20,
                'information' => 'Contenido 2H6T1LA, Tarjeta de Video UMA, Marca HP, SKU 1756534, 1756534, Conectividad WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, 
                Disco Duro 512GB SSD + 32GB Intel® Optane™, 512GB SSD + 32GB Intel® Optane™, Garantía 1 año, 1 año, Memoria RAM 8GB, 8GB, Procesador Intel Core i7-1165G7, Intel Core i7-1165G7,
                Velocidad del procesador Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Resolución de la pantalla 1920 x 1080, 1920 x 1080, Sistema operativo
                Windows 10, Windows 10, Tamaño de la pantalla 13.3", 13.3", Tipo de pantalla FHD IPS BrightView con microbordes, FHD IPS BrightView con microbordes, Pantalla Touch No, No,Tipo de Producto
                Laptop, Laptop, Ancho (Cm) 30.65 cm, 30.65 cm, Peso 1.3 Kg, 1.3 Kg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '4',
                'name' => 'Tablet MatePad',
                'description' => "MatePad 10.4 pulgadas 2022 WiFi 4GB+128GB + M-Pencil + Teclado de regalo",
                'quantity' => 2,
                'state' => 'S',
                'price' => 800.0,
                'discount_price' => 799.0,
                'image' => 'upload/87Ly06amatrv9TpLQgOm0u3P05K5IbaAdyMIlV81.png',
                'amount_sales' => 21,
                'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
                Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '2',
                'name' => 'Tablet táctil',
                'description' => "MatePad 10.4 pulgadas 2022 WiFi 4GB+64GB + Teclado de regalo",
                'quantity' => 1,
                'state' => 'R',
                'price' => 950.0,
                'discount_price' => 949.0,
                'image' => 'upload/vlefZvSWL2YRrmHrBhyTWj8iEvjeXLipkYeIhOhQ.png',
                'amount_sales' => 30,
                'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
                Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '1',
                'name' => 'iPad',
                'description' => "MatePad 11 256GB",
                'quantity' => 1,
                'state' => 'S',
                'price' => 889.0,
                'discount_price' => 860.0,
                'image' => 'upload/TpYvK966hPczRAaPlEr8IZdGvrOcbmZg9LiWyfqD.png',
                'amount_sales' => 50,
                'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
                Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '6',
                'name' => 'Tablet Huawei',
                'description' => "MatePad 11 Grey 6GB+128GB",
                'quantity' => 2,
                'state' => 'R',
                'price' => 995.0,
                'discount_price' => 980.0,
                'image' => 'upload/hkHqUlYP2pGpT2V0BfL2T1UrPpwfCocrxFyl8DCE.png',
                'amount_sales' => 50,
                'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
                Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '7',
                'name' => 'Tablet Samsung',
                'description' => "MatePad 10.4 WiFi 6 con HMS 4GB+128GB",
                'quantity' => 1,
                'state' => 'R',
                'price' => 990.0,
                'discount_price' => 998.0,
                'image' => 'upload/QAmd4AKyshhp65jzpDuMJofSaHs6GNxrWB0X6eQd.jpg',
                'amount_sales' => 90,
                'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
                Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '9',
                'name' => 'Tablet Tab P12 Pro',
                'description' => "MatePad T 10 Blue 2GB+32GB",
                'quantity' => 3,
                'state' => 'R',
                'price' => 879.0,
                'discount_price' => 850.0,
                'image' => 'upload/5xP3NF0VUtNaHNt2dl7uKsKk7insQyXXu3oYQUbq.png',
                'amount_sales' => 100,
                'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
                Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '10',
                'name' => 'Computadora HP',
                'description' => "HP 15-ef2507la amd ryzen 5 5500u 8gb ram 512gb ssd 15.6'",
                'quantity' => 1,
                'state' => 'R',
                'price' => 1420.0,
                'discount_price' => 1415.0,
                'image' => 'upload/GmyADt7GzNBYP7lU6uFcBlEOFk0QFtRrIHeZUBhn.png',
                'amount_sales' => 80,
                'information' => 'Contenido 2H6T1LA, Tarjeta de Video UMA, Marca HP, SKU 1756534, 1756534, Conectividad WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, 
                Disco Duro 512GB SSD + 32GB Intel® Optane™, 512GB SSD + 32GB Intel® Optane™, Garantía 1 año, 1 año, Memoria RAM 8GB, 8GB, Procesador Intel Core i7-1165G7, Intel Core i7-1165G7,
                Velocidad del procesador Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Resolución de la pantalla 1920 x 1080, 1920 x 1080, Sistema operativo
                Windows 10, Windows 10, Tamaño de la pantalla 13.3", 13.3", Tipo de pantalla FHD IPS BrightView con microbordes, FHD IPS BrightView con microbordes, Pantalla Touch No, No,Tipo de Producto
                Laptop, Laptop, Ancho (Cm) 30.65 cm, 30.65 cm, Peso 1.3 Kg, 1.3 Kg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '2',
                'name' => 'Computadora intel',
                'description' => "ThinkPad E15 2da Gen (15.6”, Intel)",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1230.0,
                'discount_price' => 1225.0,
                'image' => 'upload/jtKodzJinCPqvE68xhK9OW102AavxkOvZoRaUoRZ.jpg',
                'amount_sales' => 130,
                'information' => 'Contenido 2H6T1LA, Tarjeta de Video UMA, Marca HP, SKU 1756534, 1756534, Conectividad WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, 
                Disco Duro 512GB SSD + 32GB Intel® Optane™, 512GB SSD + 32GB Intel® Optane™, Garantía 1 año, 1 año, Memoria RAM 8GB, 8GB, Procesador Intel Core i7-1165G7, Intel Core i7-1165G7,
                Velocidad del procesador Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Resolución de la pantalla 1920 x 1080, 1920 x 1080, Sistema operativo
                Windows 10, Windows 10, Tamaño de la pantalla 13.3", 13.3", Tipo de pantalla FHD IPS BrightView con microbordes, FHD IPS BrightView con microbordes, Pantalla Touch No, No,Tipo de Producto
                Laptop, Laptop, Ancho (Cm) 30.65 cm, 30.65 cm, Peso 1.3 Kg, 1.3 Kg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '9',
                'name' => 'Ropero Cali',
                'description' => "Ropero Cali 5 puertas 2 cajones Almendra",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1500.0,
                'discount_price' => 1490.0,
                'image' => 'upload/ZAI1eOd9LmOKkJYVn2NeJu9hggbFYS0O4AHTbHHs.png',
                'amount_sales' => 60,
                'information' => 'El ropero Cali cuenta con 5 amplias puertas y 2 cajones para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '6',
                'name' => 'Ropero viena',
                'description' => "Ropero Viena 5 puertas corredizas espejo Nature",
                'quantity' => 1,
                'state' => 'R',
                'price' => 1900.0,
                'discount_price' => 1890.0,
                'image' => 'upload/FDN05GtfQ22733YuMU2lJxkXS5pgroeaSg81XBg0.png',
                'amount_sales' => 140,
                'information' => 'El ropero Viena cuenta con 5 amplias puertas corredizas para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '2',
                'name' => 'Ropero Cali',
                'description' => "Ropero Cali 6 puertas 5 cajones Nature",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1400.0,
                'discount_price' => 1390.0,
                'image' => 'upload/Q3AUlFpqeuxPKrIiM9YkvAdTQ4ot6WGQejfns5wS.png',
                'amount_sales' => 60,
                'information' => 'El ropero Cali cuenta con 6 amplias puertas y 5 cajones nature para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '3',
                'name' => 'Ropero Capri',
                'description' => "Ropero Capri 5 puertas y 2 cajones Almendra",
                'quantity' => 1,
                'state' => 'R',
                'price' => 850.0,
                'discount_price' => 840.0,
                'image' => 'upload/sUjcHF7MaAvXmU2AnguklxAPs8wHwdK0Ax39U9UG.png',
                'amount_sales' => 90,
                'information' => 'El ropero Capri cuenta con 5 amplias puertas y 2 cajones almendra para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '8',
                'name' => 'Ropero karim',
                'description' => "Ropero karim 4 puertas",
                'quantity' => 1,
                'state' => 'S',
                'price' => 700.0,
                'discount_price' => 699.0,
                'image' => 'upload/Zfj0WOUeMq9xSFgurBOVPs5uI3uCYfw0Opzg1jFy.png',
                'amount_sales' => 210,
                'information' => 'El ropero karim cuenta con 4 amplias puertas para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '10',
                'name' => 'Ropero Rustic',
                'description' => "Ropero 6P 2C Niza Rustic 5 puertas",
                'quantity' => 1,
                'state' => 'R',
                'price' => 1000.0,
                'discount_price' => 980.0,
                'image' => 'upload/tCXn7knX6Yk4DJK73MtjIZBHNfWR8uBGvLblGFkK.png',
                'amount_sales' => 100,
                'information' => 'El ropero Rustic cuenta con 5 amplias puertas para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('products')->insert($data);
    }
}
