<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'category_id' => '1',
                'name' => 'Pulsera de oro',
                'description' => 'Pulsera tania roffe rijida en baño de oro 18k',
                'quantity' => 60,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010101.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pulsera de oro',
                'description' => 'Set Pulsera Pandora Corazón y Corona Mujer',
                'quantity' => 40,
                'price' => 125.0,
                'discount_price' => 125.0,
                'image' => 'joyeria/20221010102.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pulsera de oro',
                'description' => 'Set Pulsera Pandora y Charm Corazón Mujer',
                'quantity' => 40,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010103.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pendientes de plata',
                'description' => 'Aretes Tous de plata con perla Tous',
                'quantity' => 50,
                'price' => 115.0,
                'discount_price' => 115.0,
                'image' => 'joyeria/20221010104.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Collar de oro',
                'description' => 'Collar XXS de oro blanco Sweet Doll Tous',
                'quantity' => 40,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010105.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pendiente de oro',
                'description' => 'Charm Colgante Trébol',
                'quantity' => 60,
                'price' => 125.0,
                'discount_price' => 125.0,
                'image' => 'joyeria/20221010106.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pendiente de oro',
                'description' => 'Charm Colgante Por Siempre Hermanas',
                'quantity' => 50,
                'price' => 115.0,
                'discount_price' => 115.0,
                'image' => 'joyeria/20221010108.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pendiente de oro',
                'description' => 'Charm Mono Brill798054cz',
                'quantity' => 40,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010109.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Anillo de oro',
                'description' => 'Anillo Pandora 190986cz',
                'quantity' => 40,
                'price' => 125.0,
                'discount_price' => 125.0,
                'image' => 'joyeria/20221010120.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Cadena de oro',
                'description' => 'Cadena lea jewelry catalina en plata 925 con enchape de oro 18k',
                'quantity' => 50,
                'price' => 145.0,
                'discount_price' => 145.0,
                'image' => 'joyeria/20221010121.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Arete de oro',
                'description' => 'Arete maisha jewellery pearl bow bañado en oro fino',
                'quantity' => 60,
                'price' => 145.0,
                'discount_price' => 145.0,
                'image' => 'joyeria/20221010122.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes guess colección tropical sun',
                'quantity' => 40,
                'price' => 142.0,
                'discount_price' => 142.0,
                'image' => 'joyeria/20221010123.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes guess colección solitaire',
                'quantity' => 40,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010124.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes guess colección heart to heart',
                'quantity' => 50,
                'price' => 115.0,
                'discount_price' => 115.0,
                'image' => 'joyeria/20221010126.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier marquet baño oro 18k',
                'quantity' => 35,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010127.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier etre baño oro 18k',
                'quantity' => 35,
                'price' => 135.0,
                'discount_price' => 135.0,
                'image' => 'joyeria/20221010129.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier lumiere baño oro 18k',
                'quantity' => 35,
                'price' => 132.0,
                'discount_price' => 132.0,
                'image' => 'joyeria/20221010130.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier eclat baño oro 18k',
                'quantity' => 60,
                'price' => 145.0,
                'discount_price' => 145.0,
                'image' => 'joyeria/20221010131.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier energie baño oro 18k',
                'quantity' => 35,
                'price' => 135.0,
                'discount_price' => 135.0,
                'image' => 'joyeria/20221010132.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier elles baño plata',
                'quantity' => 40,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010133.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier chou baño oro 18k',
                'quantity' => 40,
                'price' => 132.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010134.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes crepier couleur baño oro 18k',
                'quantity' => 40,
                'price' => 130.0,
                'discount_price' => 130.0,
                'image' => 'joyeria/20221010135.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Collar de oro',
                'description' => 'Collar crepier couleur baño oro 18k',
                'quantity' => 60,
                'price' => 135.0,
                'discount_price' => 135.0,
                'image' => 'joyeria/20221010136.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Pendientes de oro',
                'description' => 'Pendientes tous sweet dolls de oro amarillo de 18 quilates',
                'quantity' => 35,
                'price' => 142.0,
                'discount_price' => 142.0,
                'image' => 'joyeria/202210101208.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '1',
                'name' => 'Aretes de oro',
                'description' => 'Aretes guess colección g shine',
                'quantity' => 60,
                'price' => 132.0,
                'discount_price' => 132.0,
                'image' => 'joyeria/202210101255.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],  









            [
                'category_id' => '2',
                'name' => 'Medias Nike',
                'description' => 'Pack 3 Media deportivas nike',
                'quantity' => 20,
                'price' => 35.0,
                'discount_price' => 19.0,
                'image' => 'prendas/media1.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Medias Adidas',
                'description' => 'Pack 3 Media deportivas adidas',
                'quantity' => 20,
                'price' => 30.0,
                'discount_price' => 14.0,
                'image' => 'prendas/media2.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Calcetines',
                'description' => 'Pack 3 Media tobilleras Depor Mujer',
                'quantity' => 20,
                'price' => 20.0,
                'discount_price' => 19.0,
                'image' => 'prendas/media3.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Polo paqta',
                'description' => 'Paqta polo blue company',
                'quantity' => 20,
                'price' => 65.0,
                'discount_price' => 36.0,
                'image' => 'prendas/camiseta1.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Camiseta de la U',
                'description' => 'Camiseta para hombre marathon universitario color verde',
                'quantity' => 20,
                'price' => 200.0,
                'discount_price' => 190.0,
                'image' => 'prendas/camiseta2.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Pantalon jean',
                'description' => 'Jean lois para hombre bruins',
                'quantity' => 20,
                'price' => 150.0,
                'discount_price' => 140.0,
                'image' => 'prendas/pantalon.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Casaca de la U',
                'description' => 'Casaca para niño marathon universitario',
                'quantity' => 20,
                'price' => 135.0,
                'discount_price' => 109.0,
                'image' => 'prendas/polera1.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Polera Terrex - Azul',
                'description' => 'Parka adidas para mujer poliéster terrex multi',
                'quantity' => 20,
                'price' => 250.0,
                'discount_price' => 150.0,
                'image' => 'prendas/polera2.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Polera Terrex - Blanco',
                'description' => 'Polera adidas para mujer terrex everyhike',
                'quantity' => 20,
                'price' => 255.0,
                'discount_price' => 165.0,
                'image' => 'prendas/polera3.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Camiseta Juventus',
                'description' => 'Camiseta fútbol hombre adidas juventus',
                'quantity' => 20,
                'price' => 150.0,
                'discount_price' => 140.0,
                'image' => 'prendas/polera4.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Polera Kappa - Azul',
                'description' => 'Polo kappa (Azul) para hombre de algodón ',
                'quantity' => 20,
                'price' => 100.0,
                'discount_price' => 90.0,
                'image' => 'prendas/polera5.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Polera Kappa - Negro',
                'description' => 'Polo kappa (Negro) para hombre de algodón ',
                'quantity' => 20,
                'price' => 100.0,
                'discount_price' => 90.0,
                'image' => 'prendas/polera6.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Polera Adidas',
                'description' => 'Polera adidas para hombre poliéster terrex multi',
                'quantity' => 20,
                'price' => 200.0,
                'discount_price' => 190.0,
                'image' => 'prendas/polera7.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Short de la U',
                'description' => 'Short para hombre marathon universitario',
                'quantity' => 20,
                'price' => 120.0,
                'discount_price' => 110.0,
                'image' => 'prendas/short.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Short Kappa',
                'description' => 'Short kappa para hombre',
                'quantity' => 20,
                'price' => 80.0,
                'discount_price' => 70.0,
                'image' => 'prendas/short2.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '2',
                'name' => 'Licra Adidas',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'prendas/lanaRohades.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Accesorios
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/anillo2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/anillo3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/anillos.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/billetera.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/billetera2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/billetera3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/billetera4.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/billetera5.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/billetera6.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/bolso.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/bolso2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/bolso3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/collar.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/collar2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/correa.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/correa2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/gorro_de_lana.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/gorro_de_lana2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/gorro_de_lana3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/lentes.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/lentes2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/lentes3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/monedero.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/monedero2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/monedero3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/muñequera.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/muñequera2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/muñequera3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/pulsera.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/pulsera2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/pulsera3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/tobilleras.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/tobilleras2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/vincha.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '3',
                'name' => 'anillo',
                'description' => 'Malla adidas para mujer poliéster own the run',
                'quantity' => 20,
                'price' => 90.0,
                'discount_price' => 80.0,
                'image' => 'accesorios/vincha2.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            

            // [
            //     'category_id' => '9',
            //     'user_id' => '3',
            //     'name' => 'Celular',
            //     'description' => 'Samsung Galaxy S20',
            //     'published' => 15,
            //     'sold' => 12,
            //     'state' => 'S',
            //     'price' => 1500.0,
            //     'discount_price' => 1400.0,
            //     'image' => 'upload/3Oeisd4iRGZKBdGSmNonWzrEOK9LYG08RrKsFYcp.jpg',
            //     'information' => 'El samsung galaxy s20 fan edition ofrece varias opciones en cuanto a colores, además su acabado lo hace ver elegante. asimismo, con sus 4 curvaturas a los lados le permite a cualquiera mantener un mejor agarre. su pantalla infinity-o es una dynamic amoled de 6.5 pulgadas con resolución full hd+ que ofrece una tasa de refrescamiento de 120hz, de esa manera tendrás una mejor experiencia de navegación sin tanta vibración. 
            //     por otro lado, posee un lector de huella digital que se encuentra en la pantalla y su cámara frontal casi ni se percibe. su aspecto es de 20:9, el espacio suficiente para disfrutar de series, películas, juegos y más. la pantalla del galaxy s20 fe cuenta con una tasa de refresco de 120hz (la más rápida) lo que te permite ver videos de gran calidad así como disfrutar de juegos de tipo fps como fornite, cod mobile o free fire.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '4',
            //     'user_id' => '2',
            //     'name' => 'Coputadora HP',
            //     'description' => "Laptop HP DQ2055WM 4gb 256gb SSD 14'",
            //     'published' => 21,
            //     'sold' => 20,
            //     'state' => 'S',
            //     'price' => 1000.0,
            //     'discount_price' => 990.0,
            //     'image' => 'upload/LsaJ9FDjaxQtW3fTBSRAI6tnqGmBGTYaQFtGFiCd.jpg',
            //     'information' => 'Contenido 2H6T1LA, Tarjeta de Video UMA, Marca HP, SKU 1756534, 1756534, Conectividad WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, 
            //     Disco Duro 512GB SSD + 32GB Intel® Optane™, 512GB SSD + 32GB Intel® Optane™, Garantía 1 año, 1 año, Memoria RAM 8GB, 8GB, Procesador Intel Core i7-1165G7, Intel Core i7-1165G7,
            //     Velocidad del procesador Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Resolución de la pantalla 1920 x 1080, 1920 x 1080, Sistema operativo
            //     Windows 10, Windows 10, Tamaño de la pantalla 13.3", 13.3", Tipo de pantalla FHD IPS BrightView con microbordes, FHD IPS BrightView con microbordes, Pantalla Touch No, No,Tipo de Producto
            //     Laptop, Laptop, Ancho (Cm) 30.65 cm, 30.65 cm, Peso 1.3 Kg, 1.3 Kg',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '5',
            //     'user_id' => '4',
            //     'name' => 'Tablet MatePad',
            //     'description' => "MatePad 10.4 pulgadas 2022 WiFi 4GB+128GB + M-Pencil + Teclado de regalo",
            //     'published' => 30,
            //     'sold' => 21,
            //     'state' => 'S',
            //     'price' => 800.0,
            //     'discount_price' => 799.0,
            //     'image' => 'upload/87Ly06amatrv9TpLQgOm0u3P05K5IbaAdyMIlV81.png',
            //     'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
            //     Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '5',
            //     'user_id' => '2',
            //     'name' => 'Tablet táctil',
            //     'description' => "MatePad 10.4 pulgadas 2022 WiFi 4GB+64GB + Teclado de regalo",
            //     'published' => 35,
            //     'sold' => 30,
            //     'state' => 'R',
            //     'price' => 950.0,
            //     'discount_price' => 949.0,
            //     'image' => 'upload/vlefZvSWL2YRrmHrBhyTWj8iEvjeXLipkYeIhOhQ.png',
            //     'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
            //     Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '5',
            //     'user_id' => '1',
            //     'name' => 'iPad',
            //     'description' => "MatePad 11 256GB",
            //     'published' => 58,
            //     'sold' => 50,
            //     'state' => 'S',
            //     'price' => 889.0,
            //     'discount_price' => 860.0,
            //     'image' => 'upload/TpYvK966hPczRAaPlEr8IZdGvrOcbmZg9LiWyfqD.png',
            //     'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
            //     Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '5',
            //     'user_id' => '6',
            //     'name' => 'Tablet Huawei',
            //     'description' => "MatePad 11 Grey 6GB+128GB",
            //     'published' => 78,
            //     'sold' => 50,
            //     'state' => 'R',
            //     'price' => 995.0,
            //     'discount_price' => 980.0,
            //     'image' => 'upload/hkHqUlYP2pGpT2V0BfL2T1UrPpwfCocrxFyl8DCE.png',
            //     'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
            //     Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '5',
            //     'user_id' => '7',
            //     'name' => 'Tablet Samsung',
            //     'description' => "MatePad 10.4 WiFi 6 con HMS 4GB+128GB",
            //     'published' => 99,
            //     'sold' => 90,
            //     'state' => 'R',
            //     'price' => 990.0,
            //     'discount_price' => 998.0,
            //     'image' => 'upload/QAmd4AKyshhp65jzpDuMJofSaHs6GNxrWB0X6eQd.jpg',
            //     'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
            //     Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '5',
            //     'user_id' => '9',
            //     'name' => 'Tablet Tab P12 Pro',
            //     'description' => "MatePad T 10 Blue 2GB+32GB",
            //     'published' => 126,
            //     'sold' => 100,
            //     'state' => 'R',
            //     'price' => 879.0,
            //     'discount_price' => 850.0,
            //     'image' => 'upload/5xP3NF0VUtNaHNt2dl7uKsKk7insQyXXu3oYQUbq.png',
            //     'information' => 'Alto(cm) 4.3, Ancho(cm)	17.2, Profundidad(cm) 25.5, Pantalla Computo (Pulgadas) 10.1Pulgadas, Memoria RAM 4GB, Capacidad De Disco Duro 64GB HDD, Gps	Sí, Lector Tarjeta Sim No, Velocidad Del Procesador 4 basados en Cortex-A73a2.0GHz+4basadosenCortex-A53a1.7GHz,
            //     Memoria Expandible 512, Tipo De Pantalla, Pantalla táctil IPS, Batería 5100mAh, Cámara Frontal	2MP, Cámara Principal 5MP, Sistema Operativo EMUI, Entradas USB	1, Entradas HDMI No, Garantía 12 MESES',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '4',
            //     'user_id' => '10',
            //     'name' => 'Computadora HP',
            //     'description' => "HP 15-ef2507la amd ryzen 5 5500u 8gb ram 512gb ssd 15.6'",
            //     'published' => 83,
            //     'sold' => 80,
            //     'state' => 'R',
            //     'price' => 1420.0,
            //     'discount_price' => 1415.0,
            //     'image' => 'upload/GmyADt7GzNBYP7lU6uFcBlEOFk0QFtRrIHeZUBhn.png',
            //     'information' => 'Contenido 2H6T1LA, Tarjeta de Video UMA, Marca HP, SKU 1756534, 1756534, Conectividad WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, 
            //     Disco Duro 512GB SSD + 32GB Intel® Optane™, 512GB SSD + 32GB Intel® Optane™, Garantía 1 año, 1 año, Memoria RAM 8GB, 8GB, Procesador Intel Core i7-1165G7, Intel Core i7-1165G7,
            //     Velocidad del procesador Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Resolución de la pantalla 1920 x 1080, 1920 x 1080, Sistema operativo
            //     Windows 10, Windows 10, Tamaño de la pantalla 13.3", 13.3", Tipo de pantalla FHD IPS BrightView con microbordes, FHD IPS BrightView con microbordes, Pantalla Touch No, No,Tipo de Producto
            //     Laptop, Laptop, Ancho (Cm) 30.65 cm, 30.65 cm, Peso 1.3 Kg, 1.3 Kg',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '4',
            //     'user_id' => '2',
            //     'name' => 'Computadora intel',
            //     'description' => "ThinkPad E15 2da Gen (15.6”, Intel)",
            //     'published' => 140,
            //     'sold' => 130,
            //     'state' => 'S',
            //     'price' => 1230.0,
            //     'discount_price' => 1225.0,
            //     'image' => 'upload/jtKodzJinCPqvE68xhK9OW102AavxkOvZoRaUoRZ.jpg',
            //     'information' => 'Contenido 2H6T1LA, Tarjeta de Video UMA, Marca HP, SKU 1756534, 1756534, Conectividad WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, WLAN IWiFi6AX201ax2x2MUMIMOnvP+BT5WW2Ant, 
            //     Disco Duro 512GB SSD + 32GB Intel® Optane™, 512GB SSD + 32GB Intel® Optane™, Garantía 1 año, 1 año, Memoria RAM 8GB, 8GB, Procesador Intel Core i7-1165G7, Intel Core i7-1165G7,
            //     Velocidad del procesador Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Quad Core - turbo up 4.7GHz, 3200Mhz/12MBL3, Resolución de la pantalla 1920 x 1080, 1920 x 1080, Sistema operativo
            //     Windows 10, Windows 10, Tamaño de la pantalla 13.3", 13.3", Tipo de pantalla FHD IPS BrightView con microbordes, FHD IPS BrightView con microbordes, Pantalla Touch No, No,Tipo de Producto
            //     Laptop, Laptop, Ancho (Cm) 30.65 cm, 30.65 cm, Peso 1.3 Kg, 1.3 Kg',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '12',
            //     'user_id' => '9',
            //     'name' => 'Ropero Cali',
            //     'description' => "Ropero Cali 5 puertas 2 cajones Almendra",
            //     'published' => 67,
            //     'sold' => 60,
            //     'state' => 'S',
            //     'price' => 1500.0,
            //     'discount_price' => 1490.0,
            //     'image' => 'upload/ZAI1eOd9LmOKkJYVn2NeJu9hggbFYS0O4AHTbHHs.png',
            //     'information' => 'El ropero Cali cuenta con 5 amplias puertas y 2 cajones para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '12',
            //     'user_id' => '6',
            //     'name' => 'Ropero viena',
            //     'description' => "Ropero Viena 5 puertas corredizas espejo Nature",
            //     'published' => 198,
            //     'sold' => 140,
            //     'state' => 'R',
            //     'price' => 1900.0,
            //     'discount_price' => 1890.0,
            //     'image' => 'upload/FDN05GtfQ22733YuMU2lJxkXS5pgroeaSg81XBg0.png',
            //     'information' => 'El ropero Viena cuenta con 5 amplias puertas corredizas para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '12',
            //     'user_id' => '2',
            //     'name' => 'Ropero Cali',
            //     'description' => "Ropero Cali 6 puertas 5 cajones Nature",
            //     'published' => 70,
            //     'sold' => 60,
            //     'state' => 'S',
            //     'price' => 1400.0,
            //     'discount_price' => 1390.0,
            //     'image' => 'upload/Q3AUlFpqeuxPKrIiM9YkvAdTQ4ot6WGQejfns5wS.png',
            //     'information' => 'El ropero Cali cuenta con 6 amplias puertas y 5 cajones nature para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '12',
            //     'user_id' => '3',
            //     'name' => 'Ropero Capri',
            //     'description' => "Ropero Capri 5 puertas y 2 cajones Almendra",
            //     'published' => 150,
            //     'sold' => 90,
            //     'state' => 'R',
            //     'price' => 850.0,
            //     'discount_price' => 840.0,
            //     'image' => 'upload/sUjcHF7MaAvXmU2AnguklxAPs8wHwdK0Ax39U9UG.png',
            //     'information' => 'El ropero Capri cuenta con 5 amplias puertas y 2 cajones almendra para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '12',
            //     'user_id' => '8',
            //     'name' => 'Ropero karim',
            //     'description' => "Ropero karim 4 puertas",
            //     'published' => 300,
            //     'sold' => 210,
            //     'state' => 'S',
            //     'price' => 700.0,
            //     'discount_price' => 699.0,
            //     'image' => 'upload/Zfj0WOUeMq9xSFgurBOVPs5uI3uCYfw0Opzg1jFy.png',
            //     'information' => 'El ropero karim cuenta con 4 amplias puertas para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'category_id' => '12',
            //     'user_id' => '10',
            //     'name' => 'Ropero Rustic',
            //     'description' => "Ropero 6P 2C Niza Rustic 5 puertas",
            //     'published' => 135,
            //     'sold' => 100,
            //     'state' => 'R',
            //     'price' => 1000.0,
            //     'discount_price' => 980.0,
            //     'image' => 'upload/tCXn7knX6Yk4DJK73MtjIZBHNfWR8uBGvLblGFkK.png',
            //     'information' => 'El ropero Rustic cuenta con 5 amplias puertas para que almacenes gran cantidad de ropa, además cuenta con 2 cajones. Completamente fabricado en MDP, aglomerado muy utilizado en la fabricación de muebles por su durabilidad y resistencia al apolillamiento.',
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
        ];

        DB::table('products')->insert($data);
    }
}
