<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'category_id' => '1',
                'user_id' => '2',
                'name' => 'Playstation 5',
                'description' => 'Playstation 5',
                'quantity' => 1,
                'state' => 'S',
                'price' => 2000.0,
                'discount_price' => 1900.0,
                'image' => 'upload/jwgoNfuJlXMDJ5SibyJFTC7BtwaI1GtkxwTwWbUh.jpg',
                'amount_sales' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '3',
                'name' => 'Celular',
                'description' => 'Samsung Galaxy S20',
                'quantity' => 1,
                'state' => 'S',
                'price' => 1500.0,
                'discount_price' => 1400.0,
                'image' => 'upload/3Oeisd4iRGZKBdGSmNonWzrEOK9LYG08RrKsFYcp.jpg',
                'amount_sales' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '2',
                'name' => 'Coputadora HP',
                'description' => "Laptop HP DQ2055WM 4gb 256gb SSD 14'",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1000.0,
                'discount_price' => 990.0,
                'image' => 'upload/LsaJ9FDjaxQtW3fTBSRAI6tnqGmBGTYaQFtGFiCd.jpg',
                'amount_sales' => 20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '4',
                'name' => 'Tablet MatePad',
                'description' => "MatePad 10.4 pulgadas 2022 WiFi 4GB+128GB + M-Pencil + Teclado de regalo",
                'quantity' => 2,
                'state' => 'S',
                'price' => 800.0,
                'discount_price' => 799.0,
                'image' => 'upload/87Ly06amatrv9TpLQgOm0u3P05K5IbaAdyMIlV81.png',
                'amount_sales' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '2',
                'name' => 'Tablet táctil',
                'description' => "MatePad 10.4 pulgadas 2022 WiFi 4GB+64GB + Teclado de regalo",
                'quantity' => 1,
                'state' => 'R',
                'price' => 950.0,
                'discount_price' => 949.0,
                'image' => 'upload/vlefZvSWL2YRrmHrBhyTWj8iEvjeXLipkYeIhOhQ.png',
                'amount_sales' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '1',
                'name' => 'iPad',
                'description' => "MatePad 11 256GB",
                'quantity' => 1,
                'state' => 'S',
                'price' => 889.0,
                'discount_price' => 860.0,
                'image' => 'upload/TpYvK966hPczRAaPlEr8IZdGvrOcbmZg9LiWyfqD.png',
                'amount_sales' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '6',
                'name' => 'Tablet Huawei',
                'description' => "MatePad 11 Grey 6GB+128GB",
                'quantity' => 2,
                'state' => 'R',
                'price' => 995.0,
                'discount_price' => 980.0,
                'image' => 'upload/hkHqUlYP2pGpT2V0BfL2T1UrPpwfCocrxFyl8DCE.png',
                'amount_sales' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '7',
                'name' => 'Tablet Samsung',
                'description' => "MatePad 10.4 WiFi 6 con HMS 4GB+128GB",
                'quantity' => 1,
                'state' => 'R',
                'price' => 990.0,
                'discount_price' => 998.0,
                'image' => 'upload/QAmd4AKyshhp65jzpDuMJofSaHs6GNxrWB0X6eQd.jpg',
                'amount_sales' => 90,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '5',
                'user_id' => '9',
                'name' => 'Tablet Tab P12 Pro',
                'description' => "MatePad T 10 Blue 2GB+32GB",
                'quantity' => 3,
                'state' => 'R',
                'price' => 879.0,
                'discount_price' => 850.0,
                'image' => 'upload/5xP3NF0VUtNaHNt2dl7uKsKk7insQyXXu3oYQUbq.png',
                'amount_sales' => 100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '10',
                'name' => 'Computadora HP',
                'description' => "HP 15-ef2507la amd ryzen 5 5500u 8gb ram 512gb ssd 15.6'",
                'quantity' => 1,
                'state' => 'R',
                'price' => 1420.0,
                'discount_price' => 1415.0,
                'image' => 'upload/GmyADt7GzNBYP7lU6uFcBlEOFk0QFtRrIHeZUBhn.png',
                'amount_sales' => 80,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '4',
                'user_id' => '2',
                'name' => 'Computadora intel',
                'description' => "ThinkPad E15 2da Gen (15.6”, Intel)",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1230.0,
                'discount_price' => 1225.0,
                'image' => 'upload/jtKodzJinCPqvE68xhK9OW102AavxkOvZoRaUoRZ.jpg',
                'amount_sales' => 130,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '9',
                'name' => 'Ropero Cali',
                'description' => "Ropero Cali 5 puertas 2 cajones Almendra",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1500.0,
                'discount_price' => 1490.0,
                'image' => 'upload/ZAI1eOd9LmOKkJYVn2NeJu9hggbFYS0O4AHTbHHs.png',
                'amount_sales' => 60,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '6',
                'name' => 'Ropero viena',
                'description' => "Ropero Viena 5 puertas corredizas espejo Nature",
                'quantity' => 1,
                'state' => 'R',
                'price' => 1900.0,
                'discount_price' => 1890.0,
                'image' => 'upload/FDN05GtfQ22733YuMU2lJxkXS5pgroeaSg81XBg0.png',
                'amount_sales' => 140,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '2',
                'name' => 'Ropero Cali',
                'description' => "Ropero Cali 6 puertas 5 cajones Nature",
                'quantity' => 1,
                'state' => 'S',
                'price' => 1400.0,
                'discount_price' => 1390.0,
                'image' => 'upload/Q3AUlFpqeuxPKrIiM9YkvAdTQ4ot6WGQejfns5wS.png',
                'amount_sales' => 60,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '3',
                'name' => 'Ropero Capri',
                'description' => "Ropero Capri 5 puertas y 2 cajones Almendra",
                'quantity' => 1,
                'state' => 'R',
                'price' => 850.0,
                'discount_price' => 840.0,
                'image' => 'upload/sUjcHF7MaAvXmU2AnguklxAPs8wHwdK0Ax39U9UG.png',
                'amount_sales' => 90,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '8',
                'name' => 'Ropero karim',
                'description' => "Ropero karim 4 puertas",
                'quantity' => 1,
                'state' => 'S',
                'price' => 700.0,
                'discount_price' => 699.0,
                'image' => 'upload/Zfj0WOUeMq9xSFgurBOVPs5uI3uCYfw0Opzg1jFy.png',
                'amount_sales' => 210,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'category_id' => '12',
                'user_id' => '10',
                'name' => 'Ropero Rustic',
                'description' => "Ropero 6P 2C Niza Rustic 5 puertas",
                'quantity' => 1,
                'state' => 'R',
                'price' => 1000.0,
                'discount_price' => 980.0,
                'image' => 'upload/tCXn7knX6Yk4DJK73MtjIZBHNfWR8uBGvLblGFkK.png',
                'amount_sales' => 100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('products')->insert($data);
    }
}
